image: gitlab.anx.local:4567/anexia-developme/skeleton-angular/node_base

stages:
  - test_lint

cache:
  paths:
    - node_modules/
  key: "$CI_PROJECT_ID"

before_script:
  - cd src/
  - npm install

test_test_lint:
  stage: test_lint
  script:
    - ng lint
  except:
    - tags
