image: gitlab.anx.local:4567/anexia-developme/skeleton-angular/node_base

stages:
  - code_review
  - test_code

cache:
  paths:
    - node_modules/
  key: "$CI_PROJECT_ID"

before_script:
  - cd src/
  - npm install

test_code_review:
  stage: code_review
  script:
    - ng lint
  except:
    - tags

test_code:
  stage: test_code
  script:
    - ng test --watch=false
  except:
    - tags
