cache:
  key: application_cache
  paths:
  - .cache/

before_script:
- echo 'Acquire::http { Proxy "http://10.0.60.202:3142"; };' > /etc/apt/apt.conf.d/01proxy

stages:
- setup
- test_install
- test_project

setup_cookiecutter:
  image: python:3.5-stretch
  stage: setup
  script:
  - apt-get update
  - apt-get -y install python-dev python-setuptools
  - pip install --upgrade pip
  - pip install cookiecutter
  - rm -rf .cache
  - mkdir -p .cache
  - cd .cache
  - cookiecutter ../ --no-input --overwrite-if-exists project_title='Skeleton Test'

test_install:
  image: gitlab.anx.local:4567/anexia-developme/skeleton-angular/node_base
  stage: test_install
  script:
  - cd .cache/skeleton-test
  - npm install

test_project:
  image: gitlab.anx.local:4567/anexia-developme/skeleton-angular/node_base
  stage: test_project
  script:
  - cd .cache/skeleton-test
  - npm run lint
  - npm run test
  - npm run app-build-dev
  - npm run app-build-prod
  - npm run storybook-build
  - npm run generatedocs
  cache:
    key: application_cache
    paths:
    - .cache/
    policy: pull
