image: gitlab.anx.local:4567/anexia-developme/skeleton-angular/node_base

stages:
  - code_review
  - test_code
  - build_docs
  - build_app

cache:
  paths:
    - node_modules/
  key: "$CI_PROJECT_ID"

before_script:
  - cd src/
  - npm install

code_review:
  stage: code_review
  script:
    - npm run lint
  except:
    - tags

test_code:
  stage: test_code
  script:
    - ng test --watch=false
  except:
    - tags

documentation:
  stage: build_docs
  script:
    - npm run generatedocs
  except:
    - tags
  artifacts:
    when: on_success
    expire_in: 1 month
    name: "docs_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
      - dist/docs/

storybook:
  stage: build_docs
  script:
    - npm run storybook-build
  except:
    - tags
  artifacts:
    when: on_success
    expire_in: 1 month
    name: "storybook_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
      - dist/storybook/

build_development:
  stage: build_app
  script:
    - npm run app-build-dev
  except:
    - tags
  artifacts:
    when: on_success
    expire_in: 1 month
    name: "development_build_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
      - dist/skeleton-angular/

build_production:
  stage: build_app
  script:
    - npm run app-build-prod
  except:
    - tags
  artifacts:
    when: on_success
    expire_in: 1 month
    name: "production_build_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
      - dist/skeleton-angular/
