cache:
  key: "$CI_PIPELINE_ID"
  paths:
  - .cache/

before_script:
- echo 'Acquire::http { Proxy "http://10.0.60.202:3142"; };' > /etc/apt/apt.conf.d/01proxy

stages:
- setup
- test_install
- test_project
- test_dependencies

setup_cookiecutter:
  image: python:3.5-stretch
  stage: setup
  script:
  - apt-get update
  - apt-get -y install python-dev python-setuptools
  - pip install --upgrade pip
  - pip install cookiecutter
  - rm -rf .cache/*
  - rm -rf .cache
  - mkdir -p .cache
  - cd .cache
  - cookiecutter ../ --no-input --overwrite-if-exists project_title='Skeleton Test'

test_install:
  image: gitlab.anx.local:4567/anexia-developme/skeleton-angular/node_base
  stage: test_install
  script:
  - cd .cache/skeleton-test
  - yarn install

test_project:
  image: gitlab.anx.local:4567/anexia-developme/skeleton-angular/node_base
  stage: test_project
  script:
  - cd .cache/skeleton-test
  - yarn run lint
  - yarn run test
  - yarn run app-build-dev
  - yarn run app-build-prod
  # - yarn run storybook-build - needs to be fixed
  - yarn run generatedocs -p ./projects/src/tsconfig.app.json
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
    - .cache/
    policy: pull

test_dependencies:
  image: gitlab.anx.local:4567/anexia-developme/skeleton-angular/node_base
  stage: test_dependencies
  script:
  - cd .cache/skeleton-test
  - yarn outdated
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
    - .cache/
    policy: pull
  allow_failure: true
