image: gitlab.anx.local:4567/anexia-developme/skeleton-angular/node_base

stages:
  - code_review
  - test_code
  - build_docs

cache:
  paths:
    - node_modules/
  key: "$CI_PROJECT_ID"

before_script:
  - cd src/
  - npm install

code_review:
  stage: code_review
  script:
    - npm run lint
  except:
    - tags

test_code:
  stage: test_code
  script:
    - ng test --watch=false
  except:
    - tags

documentation:
  stage: build_docs
  script:
    - npm run storybook-build
    - npm run generatedocs
  except:
    - tags
  artifacts:
    when: on_success
    expire_in: 1 month
    name: "docs_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
      - docs/
