image: gitlab.anx.local:4567/anexia-developme/skeleton-angular/node_base

stages:
- code_review
- test_code
- build_docs
- build_app

cache:
  paths:
  - node_modules/
  key: "$CI_PROJECT_ID"

before_script:
- cd src/
- yarn install

#
# CI Tasks
#

# Task for running linter
code_review:
  stage: code_review
  script:
  - yarn run lint

# Task for running tests
test_code:
  stage: test_code
  script:
  - yarn run test


# Builds the apps documentation and stores it as an artifact
# Runs only if pushed to master
documentation:
  stage: build_docs
  script:
  - yarn run generatedocs ./projects/src/tsconfig.app.json
  only:
  - master
  artifacts:
    when: on_success
    expire_in: 1 month
    name: "docs_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
    - dist/docs/


# Builds the apps storybook and stores it as an artifact
# Runs only if pushed to master
storybook:
  stage: build_docs
  script:
  - yarn run storybook-build
  only:
  - master
  artifacts:
    when: on_success
    expire_in: 1 month
    name: "storybook_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
    - dist/storybook/


# Builds the app in development mode with the development environment and stores it as an artifact
build_development:
  stage: build_app
  script:
  - yarn run app-build-dev
  artifacts:
    when: on_success
    expire_in: 1 week
    name: "development_build_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
    - dist/{{ cookiecutter.project_slug }}/


# Builds the app in development mode with the staging environment and stores it as an artifact
# Runs only if pushed to master
build_staging:
  stage: build_app
  script:
  - yarn run app-build-stage
  only:
  - master
  artifacts:
    when: on_success
    expire_in: 1 month
    name: "staging_build_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
    - dist/{{ cookiecutter.project_slug }}/


# Builds the app in production mode with the production environment and stores it as an artifact
# Runs only if pushed to master
build_production:
  stage: build_app
  script:
  - yarn run app-build-prod
  only:
  - master
  artifacts:
    when: on_success
    expire_in: 1 month
    name: "production_build_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
    - dist/{{ cookiecutter.project_slug }}/


# This is only used to verify that the app is building in production mode
# Runs only if pushed to branches other then master
build_production_test:
  stage: build_app
  script:
  - yarn run app-build-prod
  except:
  - master
  - tags


# This generates of tagged production build
build_production_tag:
  stage: build_app
  script:
  - yarn run app-build-prod
  only:
  - tags
  artifacts:
    when: on_success
    expire_in: 3 months
    name: "production_build_$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
    paths:
    - dist/{{ cookiecutter.project_slug }}/
